services:
  prowlarr:
    container_name: arr-stack-prowlarr
    image: linuxserver/prowlarr:2.0.5
    restart: unless-stopped
    volumes:
      - /mnt/docker-volumes/arr-stack/prowlarr/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kaliningrad
    networks:
      - arr-stack
      - vpn
      - proxy
    labels:
      - caddy=${PROWLARR_DOMAIN}
      - caddy.reverse_proxy={{upstreams http 9696}}

  flaresolverr:
    container_name: arr-stack-flaresolverr
    image: flaresolverr/flaresolverr:v3.4.2
    restart: unless-stopped
    environment:
      - LOG_LEVEL=error
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - PROXY_URL=socks5://mihomo:1080
      - TZ=Europe/Kaliningrad
    networks:
      - arr-stack
      - vpn

  qbittorrent:
    container_name: arr-stack-qbittorrent
    image: lscr.io/linuxserver/qbittorrent:5.1.2
    restart: unless-stopped
    ports:
      - 6881:6881/udp
    volumes:
      - /mnt/docker-volumes/arr-stack/qbittorrent/config:/config
      - /mnt/docker-volumes/arr-stack/media/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kaliningrad
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    networks:
      - arr-stack
      - proxy
    labels:
      - caddy=${QBITTORRENT_DOMAIN}
      - caddy.reverse_proxy={{upstreams http 8080}}

  sonarr:
    container_name: arr-stack-sonarr
    image: lscr.io/linuxserver/sonarr:4.0.15
    restart: unless-stopped
    volumes:
      - /mnt/docker-volumes/arr-stack/sonarr/config:/config
      - /mnt/docker-volumes/arr-stack/media/tv-shows:/tv
      - /mnt/docker-volumes/arr-stack/media/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kaliningrad
    networks:
      - arr-stack
      - vpn
      - proxy
    labels:
      - caddy=${SONARR_DOMAIN}
      - caddy.reverse_proxy={{upstreams http 8989}}

  radarr:
    container_name: arr-stack-radarr
    image: lscr.io/linuxserver/radarr:5.28.0
    restart: unless-stopped
    volumes:
      - /mnt/docker-volumes/arr-stack/radarr/config:/config
      - /mnt/docker-volumes/arr-stack/media/movies:/movies
      - /mnt/docker-volumes/arr-stack/media/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kaliningrad
    networks:
      - arr-stack
      - vpn
      - proxy
    labels:
      - caddy=${RADARR_DOMAIN}
      - caddy.reverse_proxy={{upstreams http 7878}}

  recyclarr:
    container_name: arr-stack-recyclarr
    image: recyclarr/recyclarr:7.4.1
    volumes:
      - /mnt/docker-volumes/arr-stack/recyclarr/config:/config
    environment:
      - TZ=Europe/Kaliningrad
    networks:
      - arr-stack

  jellyseerr:
    container_name: arr-stack-jellyseerr
    image: ghcr.io/fallenbagel/jellyseerr:2.7.3
    restart: unless-stopped
    volumes:
      - /mnt/docker-volumes/arr-stack/jellyseerr/config:/app/config
    environment:
      - TZ=Europe/Kaliningrad
      - LOG_LEVEL=error
      - PORT=5055
    networks:
      - arr-stack
      - proxy
    labels:
      - caddy=${JELLYSEER_DOMAIN}
      - caddy.reverse_proxy={{upstreams http 5055}}

networks:
  arr-stack:
    driver: bridge
  vpn:
    external: true
  proxy:
    external: true
