LogRequests = false
DefaultPreferredLanguage = "ru"
DefaultAdmins = ["$FIRST_ADMIN_USERNAME"]

Domain = "$DOMAIN"
BaseURL = "https://$DOMAIN"

[CreateNewPlayer]
AllowChoosingUUID = true

[RegistrationNewPlayer]
Allow = true
RequireInvite = true
