mode: rule
log-level: warning
find-process-mode: strict
unified-delay: false
tcp-concurrent: true
profile:
  store-selected: true
  store-fake-ip: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
  strict-route: true

dns:
  enable: true
  default-nameserver:
    - tls://1.1.1.1
  nameserver:
    - https://cloudflare-dns.com/dns-query

listeners:
  - listen: 0.0.0.0
    name: mixed-in
    port: 1080
    proxy: PROXY
    type: mixed
    udp: true
    users: []

proxy-providers:
  provider:
    type: http
    url: "$BASE64_PROXY_SUBSCRIPTION_URL"
    interval: 86400

proxy-groups:
  - name: PROXY
    type: select
    use:
      - provider

rules:
  - MATCH,PROXY
