services:
  mihomo:
    container_name: mihomo
    image: metacubex/mihomo:v1.19.15
    restart: unless-stopped
    volumes:
      - /mnt/docker-volumes/mihomo/config/config.yaml:/root/.config/mihomo/config.yaml
    networks:
      - tunnel
      - vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

networks:
  tunnel:
    external: true
  vpn:
    external: true
