services:
  dockge:
    container_name: dockge
    image: louislam/dockge:1.5.0
    restart: unless-stopped
    ports:
      - '5001:5001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/docker-volumes/dockge/data:/app/data
      - ${STACKS_FOLDER_PATH}:${STACKS_FOLDER_PATH}
    environment:
      - DOCKGE_STACKS_DIR=${STACKS_FOLDER_PATH}
