services:
  dockge:
    image: louislam/dockge:1.5.0
    restart: unless-stopped
    ports:
      - '5001:5001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /home/$USER/homelab-stacks/stacks:/home/$USER/homelab-stacks/stacks
    environment:
      - DOCKGE_STACKS_DIR=/home/$USER/homelab-stacks/stacks
